exclude: "modules"
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
        args: [ --notitle, --maxlevel=3 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=12000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: detect-private-key
#      - id: mixed-line-ending
#        args: [--fix=auto]
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: git://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shfmt
        args: ['-l', '-i', '2', '-ci', '-sr', '-w']
